const base_perguntas_adolescente = [
  'Qual foi a última vez que não deu tempo de chegar ao banheiro?',
  '1 ano na cadeia ou para todo o sempre com seu ex?',
  'Casa na praia sem internet ou um casebre com WiFi?',
  'Você já colocou a culpa em alguém?',
  'Já foi bloqueado em alguma rede social? Por quem?',
  'Já foi traído?',
  'Um sorriso falso ou um olhar gelado?',
  'Prefere saber a data ou causa da sua morte?',
  'Quando foi a última vez que você perdeu o controle?',
  'Qual o maior mico que você já pagou na vida?',
  'Do que você não se orgulha de já ter feito nessa vida?',
  'O que te faz gozar e não é sexo?',
  'Já foi algemado?',
  'O que você compraria agora com mil reais?',
  'Se o histórico do seu WhatsApp vazasse agora e você só pudesse apagar a conversa com uma pessoa, qual seria?',
  'Qual foi o pior fora que você já levou de um crush?',
  'Qual a coisa mais engraçada que você já fez para conquistar alguém?',
  'Qual a maior mentira que você já contou só para conquistar um crush?',
  'Qual a maior mentira que você já contou no trabalho?',
  'Seu primeiro beijo teve gosto de quê?',
  'Na reunião: peidar com barulho ou tossir e espirrar catarro em alguém?',
  'Qual é o palavrão mais feio do mundo para você?',
  'Conte sobre a maior bebedeira da sua vida.',
  'O que é uma prova de amor real para você?',
  'Por que o Zeca Pagodinho toca samba e o Exaltasamba toca pagode?',
  'Mulheres devem pagar menos em baladas?',
  'Se você tivesse que se alimentar apenas de uma comida para o resto da vida, qual seria?',
  'Pizza se come com ketchup?',
  'Qual é a criatura mais estranha com a qual você se deparou?',
  'Você acredita em extraterrestres?'
];