export const base_perguntas_infantil = [
  'Quem você levaria dessa roda para uma ilha deserta?',
  'O que você faria com 1 milhão de reais agora?',
  'Qual é a sua maior vergonha na vida?',
  'Se você pudesse mudar algo em você, o que seria?',
  'Qual foi o sonho mais estranho que você já teve?',
  'Conte um segredo ou uma curiosidade sua',
  'Se hoje fosse o seu último dia de vida, o que você faria?',
  'É verdade que ninguém te chamou para sair nessa semana?',
  'De 0 a 10, que nota você daria para o (escolha alguém) em termos de (beleza, simpatia, inteligência)?',
  'É verdade que você já ficou com alguém dessa roda?',
  'Biscoito ou bolacha? Defenda sua teoria.',
  'Coxinha pela pontinha ou pela "bundinha"?',
  'O que os olhos não vêem o coração não sente?',
  'Qual foi o pior presente que você já recebeu?',
  'Se o mundo fosse acabar e você pudesse salvar apenas uma pessoa para sobreviver, quem seria?',
  'Você já nadou pelado?',
  'Qual o seu pior hábito?',
  'É possível morrer de amor?',
  'É verdade que você já foi traído?',
  'O que não pode faltar na sua geladeira?',
  'Você passaria a noite com alguém por 1 milhão de reais?',
  'É verdade que você já mandou nudes?',
  'Como foi o seu primeiro beijo?',
  'Você já beijou mais de uma pessoa no mesmo dia? Quantas?',
  'Carnaval na folia ou no campo?',
  'Dormir pelado ou com roupa?',
  'Você ficaria tranquilo se todo o histórico do seu WhatsApp ficasse público agora?',
  'Entre quatro paredes vale tudo?',
  'Qual é o seu maior orgulho?',
  'É verdade que você ficaria com alguém que está presente aqui na roda?',
  'Você se acha bonito?',
  'Qual foi o motivo do seu último término?',
  'Para onde você viajaria agora?',
  'Mãe ou pai?',
  'Se você pudesse trazer de volta uma pessoa que já morreu, quem seria?',
  'Se você pudesse mudar algo na história da humanidade, o que mudaria?',
  'Em qual país você gostaria de morar?',
  'Qual animal você gostaria de ser?',
  'Em uma máquina do tempo, para que época da história ou momento da sua vida você voltaria?',
  'É verdade que você já mentiu brincando de verdade ou desafio?',
  'WhatsApp ou Facebook?',
  'Qual é a sua técnica de sedução infalível?',
  'O que te tira do sério?',
  'Se você só pudesse salvar uma pessoa dessa sala de um incêndio, quem você salvaria?',
  'Qual foi a maior mentira que você já contou?',
  'Bar ou balada?',
  'Como foi a primeira vez que você beijou na boca?',
  'Qual estilo de música você não suporta?',
  'Já fez xixi na rua?',
  'Qual característica você realmente valoria em um amigo?',
  'Já foi pego pela polícia por alguma coisa?',
  'Você acredita em casamento?',
  'Quem é a pessoa mais inteligente do mundo, para você?',
  'O que realmente é muito brega para você?',
  'Já comeu comida que seria jogada fora?',
  'Qual a coisa mais estranha que você ama comer?',
  'O que você gosta de cantar no chuveiro?',
  'Quando você termina de fazer vo nº2 você se despede dele?',
  'Já vomitou pelo nariz?',
  'Qual é o bicho que você tem mais medo?',
  'Quem é a pessoa que você tem mais medo?',
  'Qual é o seu filme preferido?',
  'Você prefere ser rico ou famoso?',
  'Qual a pior mentira que já contaram sobre você?',
  'Quantos dias você já ficou sem tomar banho?',
  'Você tem tatuagens?',
  'O que você não tatuaria de jeito nenhum?',
  'Você participaria do BBB?',
  'Já fez xixi na piscina?',
  'Qual o pior presente que você já ganhou?',
  'O que te faz ter vontade de fugir para outro planeta?',
  'Já comeu algum inseto?',
  'Já teve diarreia constrangedora?',
  'Coxinha se come pela pontinha ou pela bundinha?',
  'É biscoito ou é bolacha?',
  'Em quais superstições você acredita?',
  'Qual o segredo do sucesso?',
  'O que você faria se ganhasse na loteria?',
  'Qual o seu sabor de pizza preferido?',
  'Você considera pizza de sushi algo socialmente aceitável?',
  'Você acredita em vidas passadas?',
  'Se você pudesse ficar invisível, o que gostaria de observar?',
  'Por qual tipo de talento você gostaria de ser famoso e reconhecido?',
  'Qual é a comida que te faz realmente muito feliz?',
  'Se você pudesse voltar no tempo, para quando voltaria?',
  'Qual é sua bebida preferida?',
  'Qual é o prato que você melhor cozinha?',
  'Qual outro idioma você gostaria de aprender?',
  'O cliente tem sempre razão?',
  'No Halloween você escolhe doçuras ou travessuras?',
  'O que é sorte grande para você?',
  'O que é que o dinheiro não pode comprar?',
  'Você sabe trocar pneu de carro?',
  'Já pegou carona com um desconhecido?',
  'Qual a melhor invenção da face da terra?',
  'O que é terapia para você?',
  'Inverno ou verão?',
  'Você gosta mais de Copa do Mundo ou Jogos Olímpicos?',
  'Qual é a doença que você tem mais medo?',
  'Quem é um verdadeiro campeão sem medalha para você?'
];