
export const base_desafios_pesadas = [
  'Tomar um danoninho usando apenas a língua;',
  'Fazer uma lap dance (dança no colo) para alguém da roda',
  'Dar uma aula de educação sexual de uma maneira muito sexy',
  'Colocar um preservativo em uma banana ou pepino',
  'Colocar um preservativo em uma fruta com a boca',
  'Massagear alguém da roda',
  'Faça uma massagem nas costas de alguém sem usar as mãos',
  'Tirar o sutiã sem tirar a camiseta',
  'Simule uma dança em pole dance',
  'Desabotoar o sutiã de alguém usando só uma mão',
  'Fingir um orgasmo',
  'Tirar a camiseta de alguém usando a boca',
  'Sussurrar uma frase sensual no ouvido de alguém',
  'Beijar a orelha de alguém da roda',
  'Fazer um discurso como se estivesse prestes à chegar a um orgasmo',
  'Poste uma foto fazendo cara de sensual no seu stories do Instagram',
  'Recitar um poema erótico',
  'Uma rodada fazendo cafuné em alguém da roda',
  'Explique onde está o clítoris',
  'Faça uma selfie sensual',
  'Simule o seu olhar mais sexy para alguém da roda:',
  'Tomar um shot no umbigo de alguém (body shot)',
  'Sussurre no ouvido de alguém as coisas que você costuma dizer na hora do sexo',
  'Morder (de leve) o pescoço de alguém da roda',
  'Com os olhos fechados, encoste a mão em alguém da roda e adivinhe qual é a parte do corpo',
  'Passar a próxima rodada no colo de alguém',
  'Chupar uma fruta como se fosse um órgão sexual',
  'Simule sexo oral com uma fruta',
  'Masturbar uma fruta com os dedos como se você estivesse falando com outra pessoa',
  'Com o consentimento, beije alguém da roda',
  'Simular um strip tease tirando uma peça de roupa',
  'Faça uma simulação no ar da sua posição sexual favorita',
  'Coloque um cubo de gelo na boca e dê um beijo no pescoço de alguém da roda',
  'Mande uma mensagem de voz sexy para seu crush',
  'Lamber alguma parte do corpo de outra pessoa',
  'Passe creme em alguém',
  'Feche os olhos, alguém da roda te dá um beijo, você precisa adivinhar quem é',
  'Mande uma mensagem para o crush perguntando se ele quer jogar verdade ou desafio virtual',
  'Envie um sticker sexy para seu crush',
  'Publique "hoje eu tô soltinh@" no seu Facebook'
];